#ifndef TOY_AI_RUNNER_H
#define TOY_AI_RUNNER_H

/*
 * toy_ai_runner — STM32 toy AI HIL DUT contract
 *
 * This module turns the STM32 toy AI shell into a TinyODOM-compatible DUT:
 *   - waits for host START after emitting DUT READY
 *   - drives D3 active-low arm on PE9
 *   - drives D2 trigger on PD0
 *   - runs either a back-to-back or cadenced measurement phase
 *   - emits UART telemetry compatible with the repo's existing harness parser
 *
 * Key UART lines:
 *   DUT READY
 *   phase output: <back_to_back|cadenced>
 *   runs: <N>
 *   clock hz output: <cpu_clock_hz>
 *   dwt cycles per inference output: <avg_cycles>
 *   timer per inference output: <seconds_per_inference>
 *   timer per window output: <seconds_per_window>
 *
 * Legacy Phase 0 lines are preserved for continuity:
 *   STM32_AI_INIT=OK / FAIL
 *   STM32_AI_RUN=OK / FAIL
 *   STM32_AI_LATENCY_CYCLES=<avg_cycles>
 *
 * Prerequisites in main.c before calling toy_ai_run_once():
 *   - DWT_Init()               — enables DWT->CYCCNT for cycle counting
 *   - DebugCom_Init()          — configures USART1 clock source and BSP COM1
 *   - toy_ai_harness_gpio_init() — configures PE9/PD0 for harness signaling
 *
 * The network used is the one generated by generate_and_stage_stm32_toy_ai.py
 * with the legacy C API. The generated default weight mapping may resolve to
 * either an embedded array or an external flash address depending on the
 * selected toy weight-storage mode.
 */

#ifdef __cplusplus
extern "C" {
#endif

/* Configure PE9/PD0 as the active-low arm / trigger outputs used by the
 * external harness. Call this once from main.c after HAL clock setup. */
void toy_ai_harness_gpio_init(void);
void toy_ai_rtc_irq_handler(void);

/*
 * toy_ai_run_once — initialise, handshake, warm up, time, and report one DUT
 * attempt covering one configured measurement window.
 *
 * Returns:
 *    0   success
 *   -1   ai_network_create_and_init failed
 *   -2   warm-up ai_network_run returned unexpected batch count
 *   -3   START command timed out
 *   -4   measured ai_network_run returned unexpected batch count
 *   -5   required XSPI external-weight mapping failed
 *   -6   RTC initialization failed
 */
int toy_ai_run_once(void);

#ifdef __cplusplus
}
#endif

#endif /* TOY_AI_RUNNER_H */
