#ifndef TOY_AI_PHASE_CONFIG_H
#define TOY_AI_PHASE_CONFIG_H

#define TOY_AI_PHASE_BACK_TO_BACK 0
#define TOY_AI_PHASE_CADENCED 1

#define TOY_AI_SELECTED_PHASE TOY_AI_PHASE_CADENCED
#define TOY_AI_LATENCY_BUDGET_MS 200
#define TOY_AI_MEASURED_RUNS 10
#define TOY_AI_CPU_CLOCK_MHZ 600
#define TOY_AI_WAKE_MARGIN_US 5000
#define TOY_AI_MIN_SLEEP_US 5000

#endif /* TOY_AI_PHASE_CONFIG_H */
