#!/usr/bin/env python3
"""
Profile OxIOD input windows and compare them to the firmware's synthetic
uniform[0, 5] input fill. This helps determine how representative the
random Arduino inputs are for latency/energy testing.

Usage examples:
  python analysis_scripts/hil_noise_analysis/oxiod_input_profile.py --split train
  python analysis_scripts/hil_noise_analysis/oxiod_input_profile.py --split train --max-windows 5000
  python analysis_scripts/hil_noise_analysis/oxiod_input_profile.py --split train --use-calibration-cap
  python analysis_scripts/hil_noise_analysis/oxiod_input_profile.py --split train --export-header sketches/analysis_sketches/oxiod_input_data.h
"""

from __future__ import annotations

import argparse
import math
import os
import sys
from pathlib import Path
from typing import Iterable

import numpy as np

sys.path.insert(0, os.path.abspath("src"))

from data_utils_ex import import_oxiod_dataset
from nas_utils_ex import DEFAULT_CONFIG_PATH, load_config


SUB_FOLDERS = [
    "handbag/",
    "handheld/",
    "pocket/",
    "running/",
    "slow_walking/",
    "trolley/",
]

CHANNEL_NAMES = [
    "acc_x",
    "acc_y",
    "acc_z",
    "gyr_x",
    "gyr_y",
    "gyr_z",
    "mag_x",
    "mag_y",
    "mag_z",
    "step",
]


def _split_to_flag(split: str) -> int:
    split = split.lower()
    if split == "train":
        return 2
    if split == "valid":
        return 3
    if split == "test":
        return 4
    if split == "train_valid":
        return 1
    raise ValueError(f"Unknown split '{split}'. Use train, valid, test, or train_valid.")


def _percentiles(values: np.ndarray, percentiles: Iterable[float]) -> list[float]:
    return [float(v) for v in np.percentile(values, percentiles)]


def _format_array(values: Iterable[float], indent: int = 2, per_line: int = 8, fmt: str = "{:.6f}") -> str:
    """
    Format a flat array for inclusion in a C header.

    Parameters
    ----------
    values : Iterable[float]
        Values to format.
    indent : int, optional
        Number of spaces to indent each line, by default 2.
    per_line : int, optional
        Values per line, by default 8.
    fmt : str, optional
        Format string for each value, by default "{:.6f}".

    Returns
    -------
    str
        Formatted multi-line string.
    """
    values = list(values)
    lines = []
    line = " " * indent
    for idx, value in enumerate(values):
        if idx > 0 and idx % per_line == 0:
            lines.append(line.rstrip())
            line = " " * indent
        line += fmt.format(value)
        if idx != len(values) - 1:
            line += ", "
    if line.strip():
        lines.append(line.rstrip())
    return "\n".join(lines)


def _write_header(
    path: Path,
    window_size: int,
    n_channels: int,
    channel_means: np.ndarray,
    channel_stds: np.ndarray,
    channel_min: np.ndarray,
    channel_max: np.ndarray,
    channel_is_binary: np.ndarray,
    real_windows: np.ndarray,
) -> None:
    """
    Write a C header containing dataset statistics and real windows.

    Parameters
    ----------
    path : pathlib.Path
        Output header path.
    window_size : int
        Sliding window length.
    n_channels : int
        Number of channels per window.
    channel_means : np.ndarray
        Per-channel mean values.
    channel_stds : np.ndarray
        Per-channel standard deviation values.
    channel_min : np.ndarray
        Per-channel minimum values.
    channel_max : np.ndarray
        Per-channel maximum values.
    channel_is_binary : np.ndarray
        Boolean mask indicating binary channels.
    real_windows : np.ndarray
        Window tensor of shape (n_windows, window_size, n_channels).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    real_windows = real_windows.astype(np.float32, copy=False)
    flat_windows = real_windows.reshape(-1)
    header = [
        "#pragma once",
        "",
        "// Auto-generated by analysis_scripts/hil_noise_analysis/oxiod_input_profile.py",
        "// Contains dataset statistics and representative windows for firmware input.",
        "",
        "#include <stdint.h>",
        "",
        f"static const int kInputWindowSize = {window_size};",
        f"static const int kInputChannels = {n_channels};",
        f"static const int kRealWindowCount = {real_windows.shape[0]};",
        "",
        f"static const float kChannelMeans[kInputChannels] = {{",
        _format_array(channel_means, fmt="{:.6f}"),
        "};",
        "",
        f"static const float kChannelStds[kInputChannels] = {{",
        _format_array(channel_stds, fmt="{:.6f}"),
        "};",
        "",
        f"static const float kChannelMin[kInputChannels] = {{",
        _format_array(channel_min, fmt="{:.6f}"),
        "};",
        "",
        f"static const float kChannelMax[kInputChannels] = {{",
        _format_array(channel_max, fmt="{:.6f}"),
        "};",
        "",
        f"static const uint8_t kChannelIsBinary[kInputChannels] = {{",
        _format_array(channel_is_binary.astype(np.uint8), fmt="{:d}"),
        "};",
        "",
        "static const float kRealWindows[",
        "    kRealWindowCount * kInputWindowSize * kInputChannels",
        "] = {",
        _format_array(flat_windows, fmt="{:.6f}"),
        "};",
        "",
    ]
    path.write_text("\n".join(header))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Profile OxIOD input windows and compare them to uniform[0,5]."
    )
    parser.add_argument("--config", default=str(DEFAULT_CONFIG_PATH), help="Path to config YAML.")
    parser.add_argument("--split", default="train", help="train, valid, test, or train_valid.")
    parser.add_argument("--max-windows", type=int, default=None, help="Cap number of windows.")
    parser.add_argument(
        "--export-header",
        default=None,
        help="Write a C header with dataset stats and real windows.",
    )
    parser.add_argument(
        "--export-stats-csv",
        default=None,
        help="Write per-channel stats to a CSV file without exporting windows.",
    )
    parser.add_argument(
        "--real-window-count",
        type=int,
        default=10,
        help="Number of real windows to embed when exporting a header.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=1337,
        help="Random seed used when sampling real windows.",
    )
    parser.add_argument(
        "--use-calibration-cap",
        action="store_true",
        help="Use config.dataset.params.calibration_windows as max_windows.",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    max_windows = args.max_windows
    if args.use_calibration_cap:
        cap = config.dataset.params.get("calibration_windows")
        if cap is not None:
            max_windows = int(cap)

    data = import_oxiod_dataset(
        type_flag=_split_to_flag(args.split),
        useMagnetometer=True,
        useStepCounter=True,
        AugmentationCopies=0,
        dataset_folder=config.dataset.params.directory,
        sub_folders=SUB_FOLDERS,
        sampling_rate=config.dataset.params.sampling_rate_hz,
        window_size=config.dataset.params.window_size,
        stride=config.dataset.params.stride,
        verbose=False,
        max_windows=max_windows,
    )

    inputs = data.inputs
    n_windows, window_size, n_channels = inputs.shape
    flat = inputs.reshape(-1, n_channels)
    channel_means = np.mean(flat, axis=0)
    channel_stds = np.std(flat, axis=0)
    channel_min = np.min(flat, axis=0)
    channel_max = np.max(flat, axis=0)
    channel_is_binary = np.all((flat == 0.0) | (flat == 1.0), axis=0)

    uniform_mean = 2.5
    uniform_std = 5.0 / math.sqrt(12.0)
    uniform_pcts = _percentiles(np.random.uniform(0.0, 5.0, size=1_000_000), [1, 5, 50, 95, 99])

    print("OxIOD input profiling")
    print(f"  split: {args.split}")
    print(f"  windows: {n_windows}")
    print(f"  window_size: {window_size}")
    print(f"  channels: {n_channels}")
    print(f"  dataset dir: {config.dataset.params.directory}")
    print(f"  max_windows: {max_windows}")
    print("")
    print("Uniform[0,5] reference")
    print(f"  mean: {uniform_mean:.4f}")
    print(f"  std:  {uniform_std:.4f}")
    print(f"  p01/p05/p50/p95/p99: {', '.join(f'{p:.4f}' for p in uniform_pcts)}")
    print("")
    print(
        "Per-channel stats: min, p01, p05, p50, p95, p99, max, mean, std, "
        "frac_in_[0,5], mean_delta, std_ratio"
    )

    percentiles = [1, 5, 50, 95, 99]
    for idx in range(n_channels):
        name = CHANNEL_NAMES[idx] if idx < len(CHANNEL_NAMES) else f"ch_{idx}"
        values = flat[:, idx]
        p01, p05, p50, p95, p99 = _percentiles(values, percentiles)
        vmin = float(np.min(values))
        vmax = float(np.max(values))
        mean = float(np.mean(values))
        std = float(np.std(values))
        frac_in = float(np.mean((values >= 0.0) & (values <= 5.0)))
        mean_delta = mean - uniform_mean
        std_ratio = std / uniform_std if uniform_std > 0 else float("nan")
        print(
            f"{name:>6s}: "
            f"{vmin: .4f}, {p01: .4f}, {p05: .4f}, {p50: .4f}, {p95: .4f}, {p99: .4f}, "
            f"{vmax: .4f}, {mean: .4f}, {std: .4f}, {frac_in: .4f}, "
            f"{mean_delta: .4f}, {std_ratio: .4f}"
        )

    if args.export_stats_csv:
        stats_path = Path(args.export_stats_csv)
        stats_path.parent.mkdir(parents=True, exist_ok=True)
        rows = []
        for idx in range(n_channels):
            name = CHANNEL_NAMES[idx] if idx < len(CHANNEL_NAMES) else f"ch_{idx}"
            values = flat[:, idx]
            p01, p05, p50, p95, p99 = _percentiles(values, percentiles)
            rows.append(
                {
                    "channel": name,
                    "min": float(np.min(values)),
                    "p01": p01,
                    "p05": p05,
                    "p50": p50,
                    "p95": p95,
                    "p99": p99,
                    "max": float(np.max(values)),
                    "mean": float(np.mean(values)),
                    "std": float(np.std(values)),
                    "frac_in_0_5": float(np.mean((values >= 0.0) & (values <= 5.0))),
                    "is_binary": bool(np.all((values == 0.0) | (values == 1.0))),
                }
            )
        import csv

        with stats_path.open("w", newline="") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
        print(f"\nWrote stats CSV: {stats_path}")

    if args.export_header:
        header_path = Path(args.export_header)
        if args.real_window_count <= 0:
            raise ValueError("real_window_count must be positive.")
        if args.real_window_count > n_windows:
            raise ValueError(
                f"real_window_count ({args.real_window_count}) exceeds available windows ({n_windows})."
            )
        rng = np.random.default_rng(args.seed)
        indices = rng.choice(n_windows, size=args.real_window_count, replace=False)
        real_windows = inputs[indices]
        _write_header(
            header_path,
            window_size=window_size,
            n_channels=n_channels,
            channel_means=channel_means,
            channel_stds=channel_stds,
            channel_min=channel_min,
            channel_max=channel_max,
            channel_is_binary=channel_is_binary,
            real_windows=real_windows,
        )
        print(f"\nWrote header: {header_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
