#ifndef TOY_AI_RUNNER_H
#define TOY_AI_RUNNER_H

/*
 * toy_ai_runner — Phase 0 single-shot AI inference shell
 *
 * Provides one function that initialises the ST Edge AI network, runs a
 * warm-up inference followed by a DWT-timed inference, and emits three
 * parseable UART tokens:
 *
 *   STM32_AI_INIT=OK              (or FAIL with error codes)
 *   STM32_AI_RUN=OK               (or FAIL with batch count)
 *   STM32_AI_LATENCY_CYCLES=<n>   (CPU cycles for one inference)
 *
 * These tokens are the Phase 0 acceptance criteria.  The smoke test script
 * (smoke_test_stm32_toy_ai.py) watches for all three and exits 0 on PASS.
 *
 * Prerequisites in main.c before calling toy_ai_run_once():
 *   - DWT_Init()       — enables DWT->CYCCNT for cycle counting
 *   - DebugCom_Init()  — configures USART1 clock source and BSP COM1
 *
 * The network used is the one generated by generate_and_stage_stm32_toy_ai.py
 * (non-binary legacy path, --c-api legacy).  Weights are embedded in the ELF;
 * no external flash or absolute memory address is required.
 */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * toy_ai_run_once — initialise, warm up, time, and report one inference.
 *
 * Returns:
 *    0   success — all three UART tokens emitted
 *   -1   ai_network_create_and_init failed
 *   -2   warm-up ai_network_run returned unexpected batch count
 *   -3   timed ai_network_run returned unexpected batch count
 */
int toy_ai_run_once(void);

#ifdef __cplusplus
}
#endif

#endif /* TOY_AI_RUNNER_H */
